language: scala
sudo: false

jdk:
  - oraclejdk8
  - oraclejdk7

scala:
  - 2.11.6
  - 2.10.5

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.sbt/launchers/

script:
  - sbt ++$TRAVIS_SCALA_VERSION travis
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - sbt coveralls
